name: 自动部署

on:
  # 触发条件1：blog 分支收到 push 后执行任务。
  push:
    branches:
      - blog
  # 触发条件2：手动按钮
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v3
        with:
          ref: blog

      - name: 安装Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org

      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: 打包构建
        run: |
            npm run build

      - name: 部署分支
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: blog-pages
          FOLDER: docs/.vuepress/dist

